# Default values for InternalLB Webhook Admission Controller
rbac:
  create: true

admissionRegistration:
  # valid values are "ValidatingWebhookConfiguration", and "MutatingWebhookConfiguration"
  kind: MutatingWebhookConfiguration
  path: /mutating-services
  # valid values are "Ignore" and "Fail"
  failurePolicy: Ignore
controller:
  image: lachlanevenson/internallb-webhook-admission-controller
  imageTag: v0.1.0
  imagePullPolicy: Always
  serviceAccount: internallb-webhook-admission-controller
  serviceAnnotationKey: service.beta.kubernetes.io/azure-load-balancer-internal
  serviceAnnotationValue: "true"
  tls:
    # Admission controller server will inherit this CA from the
    # extension-apiserver-authentication ConfigMap if available.
    requestHeaderCA:
  service:
    # Type of service; valid values are "LoadBalancer" and "NodePort"
    # NodePort is useful if deploying on bare metal or hacking locally on
    # minikube
    type: NodePort
    port: 443
    targetPort: 8443
